# Generated by Django 2.2.15 on 2020-09-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_demo'),
        ('users', '0002_auto_20200901_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_new_app', to='home.Demo'),
        ),
    ]
